name: Release
on:
  push:
    branches:
      - master
jobs:
  Release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: npm
      
      - name: Install Deps
        run: |
          yarn install
      
      - name: Package
        run: |
          zip -r tm-plugin_ldapUserAuth.zip node_modules *.js *.json

      - name: tagging
        run: |
          echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.tagging.outputs.tag }}
          tag_name: ${{ steps.tagging.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tm-plugin_ldapUserAuth.zip
          asset_name: tm-plugin_ldapUserAuth.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}